# Generated by Django 6.0.6 on 2026-07-03 14:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bep20_address', models.CharField(blank=True, default='', max_length=255)),
                ('trc20_address', models.CharField(blank=True, default='', max_length=255)),
                ('telegram_link', models.CharField(blank=True, default='https://t.me/cryptostacker', max_length=255)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('min_withdraw', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=12)),
                ('referral_commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.12'), max_digits=5)),
                ('daily_bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=12)),
                ('daily_bonus_referrals', models.IntegerField(default=3)),
                ('investment_lock_days', models.IntegerField(default=7)),
                ('about_text', models.TextField(blank=True, default='Crypto Stacker is a professional crypto trading platform. We invest your deposits in crypto trading markets and share daily profits with you. Stack your balance every 24 hours to earn tier-based returns on your total balance.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='network',
            field=models.CharField(choices=[('BEP20', 'BEP20'), ('TRC20', 'TRC20')], default='BEP20', max_length=10),
        ),
        migrations.AddField(
            model_name='deposit',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='deposits/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('stack', 'Stack Result'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('referral', 'Referral'), ('bonus', 'Bonus')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='stacklog',
            name='profit_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.014'), max_digits=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locked_investment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='InvestmentLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unlock_at', models.DateTimeField()),
                ('released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['unlock_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReferralTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('referral_count', models.IntegerField(default=0)),
                ('bonus_awarded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_referral_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
